### ISSUE TITLE
Java 11 build error

### ISSUE THREAD

**Issue by agazzarini** [SeaseLtd/rated-ranking-evaluator#100]
**Describe the bug**
Using a rre-project layout with Java 11 causes some weird behaviour because (probably) the different version used in the RRE artifacts building (Java 8)  

**To Reproduce**
Build RRE with Java 8, then create a sample project using the Maven archetype, and then run the RRE plugin using a maven launcher but this time using Java 11

**Expected behavior**
The evaluation process should be correctly executed. 

** Actual behaviour** 
`/Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/private/tmp/solr-project-example "-Dmaven.home=/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-Dmaven.ext.class.path=/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar" "-javaagent:/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=49491:/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/agazzarini/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.2 io.sease:rre-maven-solr-plugin:1.0:evaluate
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< com.yourcompany.whatever:solr-project-example >------------
[INFO] Building solr-project-example 1.0
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- rre-maven-solr-plugin:1.0:evaluate (default-cli) @ solr-project-example ---
[INFO] solr home defaulted to 'solr/' (could not find system property or JNDI)
[INFO] Loading container configuration from /var/folders/g4/3splwc6j543551z38mnd86zw0000gn/T/1564593526644/solr.xml
[INFO] Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
19:18:46.947 [main] ERROR io.sease.rre.persistence.impl.JsonPersistenceHandler - Caught IOException writing queries to JSON :: target/rre/evaluation.json (No such file or directory)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.811 s
[INFO] Finished at: 2019-07-31T19:18:47+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.sease:rre-maven-solr-plugin:1.0:evaluate (default-cli) on project solr-project-example: Execution default-cli of goal io.sease:rre-maven-solr-plugin:1.0:evaluate failed: An API incompatibility was encountered while executing io.sease:rre-maven-solr-plugin:1.0:evaluate: java.lang.NoSuchMethodError: org.apache.solr.client.solrj.impl.HttpClientUtil.configureClient(Lorg/apache/http/impl/client/DefaultHttpClient;Lorg/apache/solr/common/params/SolrParams;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.sease:rre-maven-solr-plugin:1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/agazzarini/.m2/repository/io/sease/rre-maven-solr-plugin/1.0/rre-maven-solr-plugin-1.0.jar
[ERROR] urls[1] = file:/Users/agazzarini/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar
[ERROR] urls[2] = file:/Users/agazzarini/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar
[ERROR] urls[3] = file:/Users/agazzarini/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[4] = file:/Users/agazzarini/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[ERROR] urls[5] = file:/Users/agazzarini/.m2/repository/io/sease/rre-search-platform-api/1.0/rre-search-platform-api-1.0.jar
[ERROR] urls[6] = file:/Users/agazzarini/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.4/jackson-databind-2.9.4.jar
[ERROR] urls[7] = file:/Users/agazzarini/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar
[ERROR] urls[8] = file:/Users/agazzarini/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar
[ERROR] urls[9] = file:/Users/agazzarini/.m2/repository/io/sease/rre-search-platform-solr-impl/1.0/rre-search-platform-solr-impl-1.0.jar
[ERROR] urls[10] = file:/Users/agazzarini/.m2/repository/org/apache/solr/solr-solrj/8.2.0/solr-solrj-8.2.0.jar
[ERROR] urls[11] = file:/Users/agazzarini/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar
[ERROR] urls[12] = file:/Users/agazzarini/.m2/repository/org/apache/httpcomponents/httpmime/4.5.6/httpmime-4.5.6.jar
[ERROR] urls[13] = file:/Users/agazzarini/.m2/repository/org/apache/zookeeper/zookeeper/3.5.5/zookeeper-3.5.5.jar
[ERROR] urls[14] = file:/Users/agazzarini/.m2/repository/org/apache/zookeeper/zookeeper-jute/3.5.5/zookeeper-jute-3.5.5.jar
[ERROR] urls[15] = file:/Users/agazzarini/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
[ERROR] urls[16] = file:/Users/agazzarini/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar
[ERROR] urls[17] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.4.19.v20190610/jetty-alpn-client-9.4.19.v20190610.jar
[ERROR] urls[18] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-alpn-java-client/9.4.19.v20190610/jetty-alpn-java-client-9.4.19.v20190610.jar
[ERROR] urls[19] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-client/9.4.19.v20190610/jetty-client-9.4.19.v20190610.jar
[ERROR] urls[20] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-http/9.4.19.v20190610/jetty-http-9.4.19.v20190610.jar
[ERROR] urls[21] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-io/9.4.19.v20190610/jetty-io-9.4.19.v20190610.jar
[ERROR] urls[22] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-util/9.4.19.v20190610/jetty-util-9.4.19.v20190610.jar
[ERROR] urls[23] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/http2/http2-client/9.4.19.v20190610/http2-client-9.4.19.v20190610.jar
[ERROR] urls[24] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/http2/http2-common/9.4.19.v20190610/http2-common-9.4.19.v20190610.jar
[ERROR] urls[25] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.4.19.v20190610/http2-hpack-9.4.19.v20190610.jar
[ERROR] urls[26] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.4.19.v20190610/http2-http-client-transport-9.4.19.v20190610.jar
[ERROR] urls[27] = file:/Users/agazzarini/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.24/jcl-over-slf4j-1.7.24.jar
[ERROR] urls[28] = file:/Users/agazzarini/.m2/repository/org/apache/solr/solr-core/6.6.6/solr-core-6.6.6.jar
[ERROR] urls[29] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-analyzers-common/6.6.6/lucene-analyzers-common-6.6.6.jar
[ERROR] urls[30] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-analyzers-kuromoji/6.6.6/lucene-analyzers-kuromoji-6.6.6.jar
[ERROR] urls[31] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-analyzers-phonetic/6.6.6/lucene-analyzers-phonetic-6.6.6.jar
[ERROR] urls[32] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-backward-codecs/6.6.6/lucene-backward-codecs-6.6.6.jar
[ERROR] urls[33] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-classification/6.6.6/lucene-classification-6.6.6.jar
[ERROR] urls[34] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-codecs/6.6.6/lucene-codecs-6.6.6.jar
[ERROR] urls[35] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-core/6.6.6/lucene-core-6.6.6.jar
[ERROR] urls[36] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-expressions/6.6.6/lucene-expressions-6.6.6.jar
[ERROR] urls[37] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-grouping/6.6.6/lucene-grouping-6.6.6.jar
[ERROR] urls[38] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-highlighter/6.6.6/lucene-highlighter-6.6.6.jar
[ERROR] urls[39] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-join/6.6.6/lucene-join-6.6.6.jar
[ERROR] urls[40] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-memory/6.6.6/lucene-memory-6.6.6.jar
[ERROR] urls[41] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-misc/6.6.6/lucene-misc-6.6.6.jar
[ERROR] urls[42] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-queries/6.6.6/lucene-queries-6.6.6.jar
[ERROR] urls[43] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-queryparser/6.6.6/lucene-queryparser-6.6.6.jar
[ERROR] urls[44] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-sandbox/6.6.6/lucene-sandbox-6.6.6.jar
[ERROR] urls[45] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-spatial-extras/6.6.6/lucene-spatial-extras-6.6.6.jar
[ERROR] urls[46] = file:/Users/agazzarini/.m2/repository/org/apache/lucene/lucene-suggest/6.6.6/lucene-suggest-6.6.6.jar
[ERROR] urls[47] = file:/Users/agazzarini/.m2/repository/com/carrotsearch/hppc/0.7.1/hppc-0.7.1.jar
[ERROR] urls[48] = file:/Users/agazzarini/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.5.4/jackson-dataformat-smile-2.5.4.jar
[ERROR] urls[49] = file:/Users/agazzarini/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.4.0/caffeine-2.4.0.jar
[ERROR] urls[50] = file:/Users/agazzarini/.m2/repository/com/google/protobuf/protobuf-java/3.1.0/protobuf-java-3.1.0.jar
[ERROR] urls[51] = file:/Users/agazzarini/.m2/repository/com/tdunning/t-digest/3.1/t-digest-3.1.jar
[ERROR] urls[52] = file:/Users/agazzarini/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[53] = file:/Users/agazzarini/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
[ERROR] urls[54] = file:/Users/agazzarini/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar
[ERROR] urls[55] = file:/Users/agazzarini/.m2/repository/commons-fileupload/commons-fileupload/1.3.2/commons-fileupload-1.3.2.jar
[ERROR] urls[56] = file:/Users/agazzarini/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[57] = file:/Users/agazzarini/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
[ERROR] urls[58] = file:/Users/agazzarini/.m2/repository/info/ganglia/gmetric4j/gmetric4j/1.0.7/gmetric4j-1.0.7.jar
[ERROR] urls[59] = file:/Users/agazzarini/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.2/metrics-core-3.2.2.jar
[ERROR] urls[60] = file:/Users/agazzarini/.m2/repository/io/dropwizard/metrics/metrics-ganglia/3.2.2/metrics-ganglia-3.2.2.jar
[ERROR] urls[61] = file:/Users/agazzarini/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.2.2/metrics-graphite-3.2.2.jar
[ERROR] urls[62] = file:/Users/agazzarini/.m2/repository/io/dropwizard/metrics/metrics-jetty9/3.2.2/metrics-jetty9-3.2.2.jar
[ERROR] urls[63] = file:/Users/agazzarini/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.2.2/metrics-jvm-3.2.2.jar
[ERROR] urls[64] = file:/Users/agazzarini/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
[ERROR] urls[65] = file:/Users/agazzarini/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar
[ERROR] urls[66] = file:/Users/agazzarini/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[67] = file:/Users/agazzarini/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5/eigenbase-properties-1.1.5.jar
[ERROR] urls[68] = file:/Users/agazzarini/.m2/repository/org/antlr/antlr4-runtime/4.5.1-1/antlr4-runtime-4.5.1-1.jar
[ERROR] urls[69] = file:/Users/agazzarini/.m2/repository/org/apache/calcite/calcite-core/1.11.0/calcite-core-1.11.0.jar
[ERROR] urls[70] = file:/Users/agazzarini/.m2/repository/org/apache/calcite/calcite-linq4j/1.11.0/calcite-linq4j-1.11.0.jar
[ERROR] urls[71] = file:/Users/agazzarini/.m2/repository/org/apache/calcite/avatica/avatica-core/1.9.0/avatica-core-1.9.0.jar
[ERROR] urls[72] = file:/Users/agazzarini/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[73] = file:/Users/agazzarini/.m2/repository/org/apache/curator/curator-client/2.8.0/curator-client-2.8.0.jar
[ERROR] urls[74] = file:/Users/agazzarini/.m2/repository/org/apache/curator/curator-framework/2.8.0/curator-framework-2.8.0.jar
[ERROR] urls[75] = file:/Users/agazzarini/.m2/repository/org/apache/curator/curator-recipes/2.8.0/curator-recipes-2.8.0.jar
[ERROR] urls[76] = file:/Users/agazzarini/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.4/hadoop-annotations-2.7.4.jar
[ERROR] urls[77] = file:/Users/agazzarini/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.4/hadoop-auth-2.7.4.jar
[ERROR] urls[78] = file:/Users/agazzarini/.m2/repository/org/apache/hadoop/hadoop-common/2.7.4/hadoop-common-2.7.4.jar
[ERROR] urls[79] = file:/Users/agazzarini/.m2/repository/org/apache/hadoop/hadoop-hdfs/2.7.4/hadoop-hdfs-2.7.4.jar
[ERROR] urls[80] = file:/Users/agazzarini/.m2/repository/org/apache/htrace/htrace-core/3.2.0-incubating/htrace-core-3.2.0-incubating.jar
[ERROR] urls[81] = file:/Users/agazzarini/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[82] = file:/Users/agazzarini/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[83] = file:/Users/agazzarini/.m2/repository/org/codehaus/janino/commons-compiler/2.7.6/commons-compiler-2.7.6.jar
[ERROR] urls[84] = file:/Users/agazzarini/.m2/repository/org/codehaus/janino/janino/2.7.6/janino-2.7.6.jar
[ERROR] urls[85] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-continuation/9.3.14.v20161028/jetty-continuation-9.3.14.v20161028.jar
[ERROR] urls[86] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-deploy/9.3.14.v20161028/jetty-deploy-9.3.14.v20161028.jar
[ERROR] urls[87] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-jmx/9.3.14.v20161028/jetty-jmx-9.3.14.v20161028.jar
[ERROR] urls[88] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-rewrite/9.3.14.v20161028/jetty-rewrite-9.3.14.v20161028.jar
[ERROR] urls[89] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-security/9.3.14.v20161028/jetty-security-9.3.14.v20161028.jar
[ERROR] urls[90] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-server/9.3.14.v20161028/jetty-server-9.3.14.v20161028.jar
[ERROR] urls[91] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.14.v20161028/jetty-servlet-9.3.14.v20161028.jar
[ERROR] urls[92] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-servlets/9.3.14.v20161028/jetty-servlets-9.3.14.v20161028.jar
[ERROR] urls[93] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-webapp/9.3.14.v20161028/jetty-webapp-9.3.14.v20161028.jar
[ERROR] urls[94] = file:/Users/agazzarini/.m2/repository/org/eclipse/jetty/jetty-xml/9.3.14.v20161028/jetty-xml-9.3.14.v20161028.jar
[ERROR] urls[95] = file:/Users/agazzarini/.m2/repository/org/locationtech/spatial4j/spatial4j/0.6/spatial4j-0.6.jar
[ERROR] urls[96] = file:/Users/agazzarini/.m2/repository/org/noggit/noggit/0.6/noggit-0.6.jar
[ERROR] urls[97] = file:/Users/agazzarini/.m2/repository/org/ow2/asm/asm/5.1/asm-5.1.jar
[ERROR] urls[98] = file:/Users/agazzarini/.m2/repository/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar
[ERROR] urls[99] = file:/Users/agazzarini/.m2/repository/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.jar
[ERROR] urls[100] = file:/Users/agazzarini/.m2/repository/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
[ERROR] urls[101] = file:/Users/agazzarini/.m2/repository/org/apache/logging/log4j/log4j-1.2-api/2.11.2/log4j-1.2-api-2.11.2.jar
[ERROR] urls[102] = file:/Users/agazzarini/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
[ERROR] urls[103] = file:/Users/agazzarini/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0.jar
[ERROR] urls[104] = file:/Users/agazzarini/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[105] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.jar
[ERROR] urls[106] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.7.4/doxia-decoration-model-1.7.4.jar
[ERROR] urls[107] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.7.4/doxia-site-renderer-1.7.4.jar
[ERROR] urls[108] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-skin-model/1.7.4/doxia-skin-model-1.7.4.jar
[ERROR] urls[109] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.jar
[ERROR] urls[110] = file:/Users/agazzarini/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[111] = file:/Users/agazzarini/.m2/repository/org/codehaus/plexus/plexus-velocity/1.2/plexus-velocity-1.2.jar
[ERROR] urls[112] = file:/Users/agazzarini/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[113] = file:/Users/agazzarini/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ERROR] urls[114] = file:/Users/agazzarini/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[115] = file:/Users/agazzarini/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar
[ERROR] urls[116] = file:/Users/agazzarini/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1.1.jar
[ERROR] urls[117] = file:/Users/agazzarini/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar
[ERROR] urls[118] = file:/Users/agazzarini/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[119] = file:/Users/agazzarini/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
[ERROR] urls[120] = file:/Users/agazzarini/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
[ERROR] urls[121] = file:/Users/agazzarini/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar
[ERROR] urls[122] = file:/Users/agazzarini/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
[ERROR] urls[123] = file:/Users/agazzarini/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
[ERROR] urls[124] = file:/Users/agazzarini/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar
[ERROR] urls[125] = file:/Users/agazzarini/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
[ERROR] urls[126] = file:/Users/agazzarini/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[127] = file:/Users/agazzarini/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[128] = file:/Users/agazzarini/.m2/repository/org/apache/maven/maven-builder-support/3.5.2/maven-builder-support-3.5.2.jar
[ERROR] urls[129] = file:/Users/agazzarini/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.1.0/maven-resolver-util-1.1.0.jar
[ERROR] urls[130] = file:/Users/agazzarini/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[131] = file:/Users/agazzarini/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
[ERROR] urls[132] = file:/Users/agazzarini/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[133] = file:/Users/agazzarini/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[134] = file:/Users/agazzarini/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[135] = file:/Users/agazzarini/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[ERROR] urls[136] = file:/Users/agazzarini/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[ERROR] urls[137] = file:/Users/agazzarini/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
[ERROR] urls[138] = file:/Users/agazzarini/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[139] = file:/Users/agazzarini/.m2/repository/io/sease/rre-core/1.0/rre-core-1.0.jar
[ERROR] urls[140] = file:/Users/agazzarini/.m2/repository/org/apache/logging/log4j/log4j-core/2.10.0/log4j-core-2.10.0.jar
[ERROR] urls[141] = file:/Users/agazzarini/.m2/repository/org/mockito/mockito-core/2.26.0/mockito-core-2.26.0.jar
[ERROR] urls[142] = file:/Users/agazzarini/.m2/repository/net/bytebuddy/byte-buddy/1.9.10/byte-buddy-1.9.10.jar
[ERROR] urls[143] = file:/Users/agazzarini/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.10/byte-buddy-agent-1.9.10.jar
[ERROR] urls[144] = file:/Users/agazzarini/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar
[ERROR] urls[145] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar
[ERROR] urls[146] = file:/Users/agazzarini/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
[ERROR] urls[147] = file:/Users/agazzarini/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar
[ERROR] urls[148] = file:/Users/agazzarini/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] `

**Comment by mattflax** [comment]
I don't see this locally, running from the command line. My steps are:

- `mvn clean install` using JDK8
- Switch to JDK11
- Generate Maven archetype for rre-maven-solr-archetype
- Change to new sample directory, comment out Sease plugin repo from pom.xml.
- `mvn clean package`

I don't get any NoSuchMethodExceptions running with JDK8, 11 and 12. Am I missing a step? I'm running on Linux, if that is any help.

(I do get file permissions exceptions when loading the data to the dummy cores, though.)

**Comment by agazzarini** [comment]
Yep, damned rush, I'm getting the same (I think): 

```
:java.nio.file.AccessDeniedException: /core1_v1.0
```
And in the same session (strange because  I'm using the embedded)

```
:java.nio.file.AccessDeniedException: /core1_v1.0
```

**Comment by mattflax** [comment]
Looks like the problem here is the `dataDir` setting in the solrConfig.xml files (in configuration_sets and in src/main/resources). It's set to `${solr.data.dir:}/${solr.core.name}`. When solr.data.dir isn't set, it tries to create the data directory in the filesystem root, which causes the permissions exception.

**Comment by agazzarini** [comment]
Yep, I completely removed that section, and the error is still there. 

Problem seems to be: the EmbeddedSolrServer completely ignores that settings, and when the SolrCore inits the metadata SnapshotManager SolrCore.dataDir is always null

**Comment by mattflax** [comment]
I set it to just `${solr.data.dir:}` in all three files and it ran successfully. Users can override it themselves, if necessary, either by hard-coding in the various solrconfig.xml files, or using a core.properties file in each config set, if they need the data to be preserved between runs.

**Comment by agazzarini** [comment]
mmm that means I have to stop a bit, because I believe I ended up having an unreliable environment
