### ISSUE TITLE
Generated Elasticsearch archetype not install dependencies.

### ISSUE THREAD

**Issue by tryantwit** [SeaseLtd/rated-ranking-evaluator#101]
Following instructions to start a new project [Maven Archetype](https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Maven%20Archetype) and getting to Step 3 fails on `mvn clean install` with "Failure to find io.sease:rre-maven-elasticsearch-plugin:jar:6.4.1 in https://repo.maven.apache.org/maven2". 

Seems related to #61.  Adding pluginRepository to POM.xml as described in above issue fixes it.

**Comment by agazzarini** [comment]
Hi @tryantwit thanks for entering this. Yes, as you said, this is related with #61, we are working on the main issue (#95) which hopefully will be fixed soon.

**Comment by agazzarini** [comment]
Hi @tryantwit we just completed a first round on the maven repository restructuring...we put RRE artifacts for supporting all major versions of Solr&ES. The closest ES 6.4.1 version available is 6.4.3. I understand that the ticket is 6 months old, sorry for such delay but it required a bit (read a lot :D) of work. 

- If, in the meantime, you upgrade to a newer ES version, here's a page [1] which lists the currently supported platform
- If you still need ES 6.4.1 just let me know, I can build and push that artifact in the maven repo

Cheers, 
Andrea

---

[1] https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Supported%20Versions
