### ISSUE TITLE
Small documentation fix

### ISSUE THREAD

**Issue by epugh** [SeaseLtd/rated-ranking-evaluator#39]
**Describe the bug**
On the maven archetype wiki page: https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Maven%20Archetype

I had to add to my sample pom.xml the pluginRepostiroy:

```

    <pluginRepositories>
      <pluginRepository>
        <id>sease</id>
        <url>https://raw.github.com/SeaseLtd/rated-ranking-evaluator/mvn-repo</url>
      </pluginRepository>
    </pluginRepositories>

```

**Comment by agazzarini** [comment]
Hi @epugh, thanks so much for entering this. Fix asap

**Comment by agazzarini** [comment]
Fixed, I added the required conf in the "Getting started", in the "existing projects" section. For new projects, the archetype section already mention that settings.
