### ISSUE TITLE
Evaluation output persistence framework

### ISSUE THREAD

**Issue by agazzarini** [SeaseLtd/rated-ranking-evaluator#54]
The RRE current implementation outputs a JSON file as result of the evaluation process.  

The issue is about creating a persistence framework for binding in a pluggable way several persistence strategies (e.g. database, Cassandra, Solr, Elasticsearch). 

Once the data will be persisted, it could be queried/used by some Reporting/BI tool.

**Comment by mattflax** [comment]
Hi Andrea,

I was wondering if you had made progress with this? I've started work on a persistence framework here: https://github.com/mattflax/rated-ranking-evaluator/tree/persistence - I'd be interested to read your thoughts on my approach (if any). I'm planning to create any number of PersistenceHandlers, all managed by a PersistenceManager class. A JsonPersistenceHandler will act in place of the current default output.

I've tried to bear in mind the conversation you had with @binarymax in the comments for #56 regarding using a timestamp in place of a version key, but I haven't got as far as implementing anything solid yet.

Thanks,
Matt

**Comment by agazzarini** [comment]
Hi @mattflax sorry again for my delay in response. I think the approach your idea is in the right direction. I just merged your PR #66 which should be about this. 

Do you think the io.sease.rre.persistence content covers the goal of this issue (i.e. the persistence contract interfaces + the JSON binding)? 

If so, we could close this issue and later open dedicated issues for the persistence providers we want to support. 

Andrea

**Comment by mattflax** [comment]
Hi Andrea,

I think the framework as it stands does cover this issue - I've successfully used it to build an Elasticsearch persistence handler (as I'm sure you've seen).

Do let me know if I can help with documentation for these additions too - I've been adding README files with details of how to use things, but you have to dig a bit to find them.

Matt

**Comment by agazzarini** [comment]
Hi Matt, great to hear and sorry for such delay in response. 
So I think we can close this and then, as mentioned, we can open new issues dedicated (when and if we want to add a new persistence provider).

The documentation, yeah, nice point. I'm not sure if you already have permissions for the Wiki, I have to check; in any case, README is good as well. When I will be able to find a decent amount of time I'll try to get the point about the current state (of software and doc).

Thanks again, 
Andrea
