### ISSUE TITLE
Error when building RRE

### ISSUE THREAD

**Issue by binarymax** [SeaseLtd/rated-ranking-evaluator#60]
Hi SeaSe!

Sorry to have to bother you with a maven build issue, but I'm not sure where else to turn.

After downloading the latest source today, cd'ing into the path, and running 'mvn clean install', the project fails to build.  I am running Java8 on a Mac.  Maven is version 3.5.4.

The maven output exceeds the allowed length of an issue, so I've put it into a gist here:
https://gist.github.com/binarymax/8bf75b86a0fac01a38874efda7d408f7

There are two files in the gist - the second 'rre-maven-output-full-stack-trace' was run with 'mvn -e clean install'

Any advice you can give on how I can successfully build would be much appreciated!

Many Thanks.

**Comment by agazzarini** [comment]
Hi @binarymax I tried on your same platform and also in a fresh Linux Mint installation. 
I wasn't able to reproduce the issue, the only thing I found (on Mint) is the following error: 

```
[ERROR] ...  error: unmappable character for encoding ASCII   
```    

I solved that, so before trying again, it's better to pull the latest version. About your error, the interesting part seems the following: 

```
[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
java.lang.ExceptionInInitializerError
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.<clinit> (AbstractZipArchiver.java:116)
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
```

Which is very strange. Could you try to re-execute a "mvn clean install"? Is that error still there? 
In case the answer is positive (i.e."the error is still there"), could you please write the exact JVM version?

Thanks,
Andrea

**Comment by binarymax** [comment]
OK I finally figured out the problem.  I installed Java8 on this new Mac, but it already had Java11 on it and was using that as default.  I switched the JAVA_HOME to jdk8 by using this command: `export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"` and then it built fine!
