### ISSUE TITLE
Solr does not allow unquoted JSON DSL in query template

### ISSUE THREAD

**Issue by mattoscln** [SeaseLtd/rated-ranking-evaluator#78]
When including JSON DSL in a Solr query template, it must be quoted or is not added to the query correctly.

**To Reproduce**
1. Add a JSON parameter to a Solr query template:
```
{
  "json": {
    "query": {
      "lucene": {
        "query": "$query"
      }
    }
  }
}
```
2. Run the evaluation process.
3. Observe that the query details have not been added to the SolrQuery (eg. the query request looks like `/select?fl=field1 field2&json=&rows=20`

**Expected behavior**
Included JSON DSL should not require quotes around the content - this will make it harder to write and increase the number of potential bugs in the query where JSON is in use.

**Comment by agazzarini** [comment]
Closed with https://github.com/SeaseLtd/rated-ranking-evaluator/pull/79
