### ISSUE TITLE
ElasticSearch persistence handler needs to be updated to support up to v7.0

### ISSUE THREAD

**Issue by magsln** [SeaseLtd/rated-ranking-evaluator#89]
Breaking changes to the way v7.0 creates indices means that the persistence handler does not work with this version. See: https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_typeless_apis_in_7_0 

Preferred solution
Update the creation of the index so that it handles the new changes

Currently just going to downgrade the ES version

**Comment by agazzarini** [comment]
Thanks for entering this @magsln

**Comment by mattflax** [comment]
Are you working on this as part of #95 @agazzarini ? I've taken a look, and I think we can use the ES7.x client for both ES6.x and ES7, though we need to use different createIndex() methods for the earlier versions.

Let me know if you'd like me to put together a PR for it. If it's covered by the work for #95, I won't worry about it.

**Comment by agazzarini** [comment]
Hi @mattoscln I'm trying to get the point about #95 but honestly at the moment I'm more focused on the Solr side. Not sure how we can proceed (i.e. if that PR would interfere with #95)

**Comment by mattflax** [comment]
Okay - I don't think the PR would interfere with #95. I'll change the ES persistence plugin to use the most recent ES client, and use basic HTTP calls for versions earlier than 7 (the ES client adds parameters that cause problems with versions earlier than 6.8).
