### ISSUE TITLE
`external-solr-impl` compatible with Solr version 6.6.x

### ISSUE THREAD

**Issue by daredevil82** [SeaseLtd/rated-ranking-evaluator#97]
I would like to integrate RRE with our existing infrastructure for relevancy analysis.  For purposes of flexibility in configuration and deployment, we would like to leverage `rre-search-platform-external-solr-impl` with our CI infrastructure.  However, after talking with @agazzarini on the Relevance Search slack, the current implementation is compatible only with 7.5.x.

We are planning to be on 7.x by EOY, but for now that update is not possible.  Having compatibility with 6.x would be a major help.

**Comment by mattflax** [comment]
I took a look into this - the HTTP client initialisation process is quite different for Solr 6 from that for Solr 7. I also had to change the Jackson versions - Solr 6 uses Jackson 2.5.x, while Solr 7 is on Jackson 2.9.x.

There's a branch on my fork of the main repo, if you're happy to build your own: https://github.com/mattflax/rated-ranking-evaluator/tree/external_solr_6.6

(I've given it a quick test against Solr 6.6.6 locally using the test data set, but haven't tested it extensively.)

@agazzarini I'm not sure the best approach to getting this released to the Maven repo, so no PR yet. Do you have any thoughts how to go about this?

**Comment by agazzarini** [comment]
Hi @mattoscln I'm working on the #95 following your approach with a slight change which should fix also this problem. Basically, after some investigation, I think we could use a fixed version (or LATEST) for Solrj, because at the end it is just sending a HTTP request.

I tried using Solrj 8 againsts Solr 8 to 4 and it works, so maybe that could be a right approach to improve the maintainability of that maven repo

**Comment by mattflax** [comment]
Yes, that sounds like a sensible approach for Solr - it's nice when things are backwards compatible!

**Comment by agazzarini** [comment]
Hi @daredevil82 we re-uploaded the RRE maven artifacts, please find here [1] the supported ES & Solr versions.

Let me know
Andrea

----
[1] https://github.com/SeaseLtd/rated-ranking-evaluator/wiki/Supported%20Versions
